# Generated by Django 4.1.5 on 2023-01-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('birthday', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('age', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=70)),
                ('citizen', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=70)),
                ('id_type', models.CharField(max_length=70)),
                ('id_no', models.CharField(max_length=70)),
                ('member', models.CharField(max_length=70)),
            ],
        ),
    ]
